server = "hunter"

[log]
level = "debug"

# web服务配置
[web]
mode = "debug"
addr = ":11008"


[ws]
proxy = "http://10.0.64.224:7890"
write_wati = 1

[http]
proxy = "http://10.0.64.224:7890"

[binance]
api_key = ""
secret_key = ""
ed25519_api_key = ""
ed25519_private_key = ""

[strage]
symbols = [["PEPEUSDT","1000PEPEUSDT"],]